#-------------------------------
# General Site Settings
baseURL = "https://jqtconsultancy.com/"
title = "JQT Consultancy"
googleAnalytics = "G-M88V762P7V" # Add your identifier. For example UA-99631805-1.
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = true  # Force Dutch to use /nl/ subdirectory

[pagination]
  pagerSize = 9

#-------------------------------
# Languages
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    languageCode = "en-US"
    weight = 20

    # English-specific parameters
    [languages.en.params]
      description = "JQT Consultancy is a company offering IT & Product services for a world transitioning to clean energy."

      [languages.en.params.hero]
        hero__title = "JQT Consultancy | Product Management & IT Services for Renewable Energy"
        hero__description = """Product Management and IT services for a clean energy future."""
        hero__image = "/images/Jeroen-landscape-medium.jpg"

  [languages.nl]
    contentDir = 'content/nl'
    languageName = 'Nederlands'
    languageCode = "nl-NL"
    weight = 10

    # Dutch-specific parameters
    [languages.nl.params]
      description = "JQT Consultancy is een bedrijf dat IT & Product diensten biedt voor een wereld die overschakelt naar schone energie."

      [languages.nl.params.hero]
        hero__title = "JQT Consultancy | Product Management & IT Diensten voor Hernieuwbare Energie"
        hero__description = """Product Management en IT diensten voor een schone energie toekomst."""
        hero__image = "/images/Jeroen-landscape-medium.jpg"

#-------------------------------
# English Menu
[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/en/"
    weight = 1

  [[languages.en.menu.main]]
    identifier = "services"
    name = "Services"
    url = "/en/services"
    weight = 2

  [[languages.en.menu.main]]
    identifier = "blogs"
    name = "Blog"
    url = "/en/blogs"
    weight = 3

  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/en/about"
    weight = 4

  [[languages.en.menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/en/contact"
    weight = 5

  [[languages.en.menu.main]]
    identifier = "wet-dba"
    name = "Wet DBA"
    url = "/en/wet-dba"
    weight = 6

#-------------------------------
# Dutch Menu
[languages.nl.menu]
  [[languages.nl.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/nl/"
    weight = 1

  [[languages.nl.menu.main]]
    identifier = "services"
    name = "Diensten"
    url = "/nl/services"
    weight = 2

  [[languages.nl.menu.main]]
    identifier = "blogs"
    name = "Blog"
    url = "/nl/blogs"
    weight = 3

  [[languages.nl.menu.main]]
    identifier = "about"
    name = "Over"
    url = "/nl/about"
    weight = 4

  [[languages.nl.menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/nl/contact"
    weight = 5

  [[languages.nl.menu.main]]
    identifier = "wet-dba"
    name = "Wet DBA"
    url = "/nl/wet-dba"
    weight = 6


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".

  [params.author]
    name = "Jeroen van der Meer"
    avatar = "images/avatar_jeroen.jpg"

  # [[params.social]]
  #   icon = "ion-logo-twitter"
  #   name = "Twitter"
  #   link = "https://twitter.com"

  # [[params.social]]
  #   icon = "ion-logo-facebook"
  #   name = "Facebook"
  #   link = "https://facebook.com"

  # [[params.social]]
  #   icon = "ion-logo-pinterest"
  #   name = "Pinterest"
  #   link = "https://pinterest.com"

  # [[params.social]]
  #   icon = "ion-logo-dribbble"
  #   name = "Dribbble"
  #   link = "https://dribbble.com"

  # [[params.social]]
  #   icon = "ion-logo-instagram"
  #   name = "Instagram"
  #   link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com/"

  [[params.social]]
    icon = "ion-ios-briefcase"
    name = "JQT Consultancy (LinkedIn)"
    link = "https://www.linkedin.com/company/86024721/"

  [[params.social]]
    icon = "ion-logo-linkedin"
    name = "Jeroen van der Meer (LinkedIn)"
    link = "https://www.linkedin.com/in/jeroenvdmeer1975/"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/

  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  # [params.mailchimp]
  #   mailchimp__title = "Get Interesting News"
  #   mailchimp__text = "Subscribe to our newsletter and we'll send you the emails of latest posts."
  #   mailchimp__identifier = "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  #   mailchimp__button__text = "Subscribe" # Add your button text

  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "f/xwpbkvoz" # Add your email for contant form

    # NOTE
    # Aditu comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  # [params.disqus]
  #   disqusShortname = "anvod-studio-aditu" # add your shortname for Disqus Comment. For example anvod-studio-aditu


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]

# Language-specific outputs for multilingual search
[languages.en.outputs]
  home = ["HTML", "RSS", "JSON"]

[languages.nl.outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
