#-------------------------------
# General Site Settings
baseURL = "https://jqtconsultancy.com/"
languageCode = "en-us"
title = "JQT Consultancy"
googleAnalytics = "G-M88V762P7V" # Add your identifier. For example UA-99631805-1.
paginate = 9


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/contact"
    weight = 4

  # [[menu.main]]
  #   identifier = "styleguide"
  #   name = "Style Guide"
  #   url = "/styleguide"
  #   weight = 4


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "JQT Consultancy is a company offering IT & Product services for a world transistioning to clean energy."

  [params.author]
    name = "Jeroen van der Meer"
    avatar = "images/avatar_jeroen.jpg"

  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "JQT Consultancy"
    hero__description = """Hi, my name is Jeroen van der Meer from JQT Consultancy BV. With a Master’s degree in Electrical Engineering and a passion for renewable energy, I offer specialized Product Owner services to help your business succeed in the renewable energy sector. My technical expertise and problem-solving skills ensure your projects are delivered with precision and innovation. I have a focus on B2B E-commerce for renewable technologies like, heat pumps, solar systems and battery storage. In the past, I have helpd teams deliver sales and installations of renewable energy systems. These workflows heavily depended on configurators, quote tools and integrations with CRM and ERP systems."""
    hero__image = "images/Project-view-with-priorities-on-iMac.png"

  # [[params.social]]
  #   icon = "ion-logo-twitter"
  #   name = "Twitter"
  #   link = "https://twitter.com"

  # [[params.social]]
  #   icon = "ion-logo-facebook"
  #   name = "Facebook"
  #   link = "https://facebook.com"

  # [[params.social]]
  #   icon = "ion-logo-pinterest"
  #   name = "Pinterest"
  #   link = "https://pinterest.com"

  # [[params.social]]
  #   icon = "ion-logo-dribbble"
  #   name = "Dribbble"
  #   link = "https://dribbble.com"

  # [[params.social]]
  #   icon = "ion-logo-instagram"
  #   name = "Instagram"
  #   link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com/"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/

  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  # [params.mailchimp]
  #   mailchimp__title = "Get Interesting News"
  #   mailchimp__text = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
  #   mailchimp__identifier = "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  #   mailchimp__button__text = "Subscribe" # Add your button text

  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "f/xwpbkvoz" # Add your email for contant form

    # NOTE
    # Aditu comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  # [params.disqus]
  #   disqusShortname = "anvod-studio-aditu" # add your shortname for Disqus Comment. For example anvod-studio-aditu


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false